version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    # network_mode: host
    networks:
      - mqtt-net
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./data-mosquitto:/mosquitto/data-mosquitto
      - ./log:/mosquitto/log
networks:
  mqtt-net:
    name: mqtt-net
    driver: bridge
